return {
	accented = Color3.fromHex("#393939"),
	default = Color3.fromHex("#1b1718"),
	elevated = Color3.fromHex("#2a2627"),
	primary = Color3.fromHex("#00dc82"),
	error = Color3.fromHex("#ff6467"),
	-- default = Color3.fromHex("#2a2627"),
	-- elevated = Color3.fromHex("#3f3f47"),
	-- accented = Color3.fromHex("#5A5A63"),
	border = Color3.fromHex("#5A5A63"),
	-- #00dc82 is the primary, so the primary bg will be darker shade
}
